version=0.1

[default.build.parameters]
debug = true
use_container = false

[default.deploy.parameters]
debug = true
stack_name = "sam-notify-aws-billing"
resolve_s3 = true
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = false
