AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Notify AWS billing

Parameters:
  NotifyDaysInterval:
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 30
    Description: "Notify days interval"
  SlackWebhookUrl:
    Type: String
    Default: ""
    NoEcho: true
    Description: "Slack Webhook URL"
  LineAccessToken:
    Type: String
    Default: ""
    NoEcho: true
    Description: "LINE Access Token"

Conditions:
  HasSlackWebhookUrl: !Not [!Equals [!Ref SlackWebhookUrl, ""]]
  HasLineAccessToken: !Not [!Equals [!Ref LineAccessToken, ""]]

Resources:
  SlackWebhookSecret:
    Type: AWS::SecretsManager::Secret
    Condition : HasSlackWebhookUrl
    Properties:
      Description: "Slack Webhook URL"
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"info": ${SlackWebhookUrl}}'
        GenerateStringKey: "info"
      Name: !Sub /{AWS::StackName}-secret-notify-aws-billing/slack-webhook-url

  LineAccessTokenSecret:
    Type: AWS::SecretsManager::Secret
    Condition : HasLineAccessToken
    Properties:
      Description: "LINE Access Token"
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"info": ${LineAccessToken}}'
        GenerateStringKey: "info"
      Name: !Sub /{AWS::StackName}-secret-notify-aws-billing/line-access-token

  BillingIamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-role-notify-aws-billing
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"

  BillingIamPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub ${AWS::StackName}-policy-notify-aws-billing
      Roles:
        - !Ref BillingIamRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "ce:GetCostAndUsage"
            Resource: "*"
          - Effect: Allow
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
          - Effect: Allow
            Action:
              - "secretsmanager:GetResourcePolicy"
              - "secretsmanager:GetSecretValue"
              - "secretsmanager:DescribeSecret"
              - "secretsmanager:ListSecretVersionIds"
            Resource:
              - !If
                - HasSlackWebhookUrl
                - !Ref SlackWebhookSecret
                - !Ref AWS::NoValue
              - !If
                - HasLineAccessToken
                - !Ref LineAccessTokenSecret
                - !Ref AWS::NoValue

  BillingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-function-notify-aws-billing
      CodeUri: function/
      Handler: index.handler
      Runtime: python3.11
      Role: !GetAtt BillingIamRole.Arn
      Timeout: 60
      Layers:
        - arn:aws:lambda:ap-northeast-1:133490724326:layer:AWS-Parameters-and-Secrets-Lambda-Extension:4
      Environment:
        Variables:
          SLACK_WEBHOOK_URL: !If
            - HasSlackWebhookUrl
            - !Sub /${AWS::StackName}-secret-notify-aws-billing/slack-webhook-url
            - !Ref AWS::NoValue
          LINE_ACCESS_TOKEN: !If
            - HasLineAccessToken
            - !Sub /${AWS::StackName}-secret-notify-aws-billing/line-access-token
            - !Ref AWS::NoValue

  BillingEventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: default
      Name: !Sub ${AWS::StackName}-rule-notify-aws-billing
      ScheduleExpression: !Sub cron(0 0 */${NotifyDaysInterval} * ? *)
      State: ENABLED
      Targets:
        - Arn: !GetAtt BillingFunction.Arn
          Id: BillingFunction

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref BillingFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt BillingEventBridgeRule.Arn

Outputs:
  FunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt BillingFunction.Arn
  EventBridgeRuleArn:
    Description: "EventBridge Rule ARN"
    Value: !GetAtt BillingEventBridgeRule.Arn
